thruster_manager:
  ros__parameters:
    # T200 Profile
    thrust_max_fwd: 5.25  # kg-f @ 16V
    thrust_max_bwd: 4.1 # kg-f @ 16V
    thrust_deadband: 0.000001
    motor_driver_deadband: 0.0625 # Scale from 0 to 1

    # Control Profil
    rate_limit: 0.3

