<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">


    <xacro:arg name="namespace" default="hi"/>
    <xacro:arg name="simulation" default="true"/>
    <xacro:arg name="density" default="1000"/>
    
    <xacro:property name="ns" value="$(arg namespace)"/>
    <xacro:property name="density" value="$(arg density)"/>

    <xacro:property name="x_size" value="0.40"/>
    <xacro:property name="y_size" value="0.25"/>
    <xacro:property name="z_size" value="0.1"/>

    <xacro:property name="mass" value="14.8"/>
        
    <!-- other props -->
    <xacro:property name="prop_mass" value="0.07"/>
    <!-- to set correct buoyancy volume with 1 % positive factor -->
    <xacro:property name="buoyant_correction" value="${1.01*pow((mass + 6*prop_mass)/(density*x_size*y_size*z_size), 1./3)}"/>
    <!-- Center of buoyancy -->
    <xacro:property name="z_cob" value="${-buoyant_correction*z_size/4}"/>
    <!-- Center of gravity -->
    <xacro:property name="z_cog" value="${-buoyant_correction*z_size}"/>

    <!-- Include the thruster Xacro file -->
    <xacro:include filename="inertial_macros.xacro"/>

    <link name="${ns}/base_link">
    </link>

    <!-- Define the base link -->
    <joint name="chassis_joint" type="fixed">
        <parent link="${ns}/base_link"/>
        <child link="${ns}/chassis"/>
        <origin xyz="0 0 0"/>
    </joint>
    
    <link name="${ns}/chassis">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.3 0.05"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.5 0.6 0.4"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.5" y="0.6" z="0.4">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!-- Add multiple thrusters with different positions and orientations -->
    <xacro:include filename="thruster.xacro"/>
    
    <xacro:thruster thruster_id="0" dir="CW" parent="chassis">
        <origin xyz="0.2 0.2 0.07" rpy="0 ${pi/4} ${pi/2}" />
    </xacro:thruster>
    <xacro:thruster thruster_id="1" dir="CCW" parent="chassis">
        <origin xyz="0 0.25 0" rpy="${pi} -${pi} 0" />
    </xacro:thruster>
    <xacro:thruster thruster_id="2" dir="CW" parent="chassis">
        <origin xyz="-0.2 0.2 -0.07" rpy="0 -${pi/4} ${pi/2}" />
    </xacro:thruster>
    <xacro:thruster thruster_id="3" dir="CCW" parent="chassis">
        <origin xyz="0.2 -0.2 0.07" rpy="0 ${pi/4} -${pi/2}" />
    </xacro:thruster>
    <xacro:thruster thruster_id="4" dir="CW" parent="chassis">
        <origin xyz="0 -0.25 0" rpy="${pi} -${pi} 0" />
    </xacro:thruster>
    <xacro:thruster thruster_id="5" dir="CCW" parent="chassis">
        <origin xyz="-0.2 -0.2 -0.07" rpy="0 -${pi/4} -${pi/2}" />
    </xacro:thruster>

    <xacro:include filename="stereo_camera.xacro"/>
    <xacro:stereo_camera parent="chassis">
        <origin xyz="0.3 0 0" rpy="0 0 0" />
    </xacro:stereo_camera>

    <!-- <xacro:include filename="imu.xacro"/> -->
    <!-- <xacro:include filename="depth_sensor.xacro"/> -->


</robot>